# Generated by Django 5.2.3 on 2025-06-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название кейса')),
                ('description', models.TextField(verbose_name='Описание кейса')),
                ('image', models.ImageField(upload_to='cases_images/', verbose_name='Изображение кейса')),
                ('tags', models.CharField(max_length=200, verbose_name='Теги')),
            ],
        ),
    ]
